# EDL MaskFormer 配置: EDL分类 + Dirichlet分割 + 匈牙利匹配 (完整EDL)
# 命名含义: edl_分类损失_分割损失_匹配方式_特殊标识

# 数据集配置
dataset:
  type: 'RIGA'
  config_path: './codes/configs/RIGA.yaml'

# 实验输出配置
experiment:
  save_dir: './exp/edl_dirichlet_hungarian_full'
  max_checkpoints: 3
  
# 训练配置
training:
  seed: 42
  epochs: 120
  batch_size: 6   # 更小batch size适应更复杂的损失
  use_amp: true
  num_workers: 4
  
  # 学习率配置 - 更保守的学习率
  learning_rate: 0.0006
  min_learning_rate: 1e-6
  
  # 优化器配置
  optimizer_type: 'AdamW'
  weight_decay: 1.5e-4  # 更强正则化
  betas: [0.9, 0.999]
  eps: 1e-8
  
  # 调度器配置
  use_cosine_scheduler: true
  warmup_epochs: 15

# 模型配置
model:
  in_channels: 3
  num_cls_classes: 12
  num_queries: 12
  
  # Backbone配置
  backbone_encoder_name: "resnet34"
  backbone_encoder_weights: "imagenet"
  backbone_decoder_channels: [256, 128, 64, 32, 16]
  backbone_use_batchnorm: true
  
  # 掩码特征配置
  mask_dim: 64
  mask_pixel_idxs: [-4, -3, -2]
  
  # Predictor配置
  predictor_nheads: 8
  predictor_dim_feedforward: 256
  predictor_dec_layers: 3
  predictor_non_object: true
  
  # EDL配置
  predictor_cls_type: 'single'
  predictor_attn_mask_type: 'uncertainty_ratio'
  predictor_uncertainty_focus_ratio: 0.3

# 损失函数配置 - EDL分类 + Dirichlet分割 + 匈牙利匹配
loss:
  num_cls_classes: 12
  
  # 匹配器配置
  matcher_cost_class: 2.5
  matcher_cost_dice: 5.0
  matcher_cost_evidence: 1.5
  matcher_cost_class_type: 'evidence'
  
  # 损失类型配置  
  cls_loss_type: 'edl'           # EDL分类损失
  seg_edl_as_dirichlet: true     # Dirichlet分割损失 (完整EDL)
  dice_on_logits: false
  
  # 权重配置 - 针对Dirichlet分割调整
  branch_weight_cls: 1.0
  branch_weight_seg: 1.2   # 增强分割分支权重
  loss_weight_cls: 1.0
  loss_weight_kl: 0.15     # 更强KL正则化
  loss_weight_dice: 0.8
  loss_weight_edl_mask: 1.2
  
  # 其他配置
  eos_coef: 0.1
  non_object: true
  annealing_steps: 15000   # 更长退火
  use_direct_matching: false  # 使用匈牙利匹配
  
  # 深监督
  use_deep_supervision: false
  ds_loss_weights: [1.0, 0.5, 0.25]
  ds_avg_type: 'mean_all'