root: /app/MultiAnn/EDLformer/data/DiscRegion/
train_list: [ 'BinRushed', 'MESSIDOR' ]
train_transform:
  - name: ToTensor
  - name: RandomHorizontalFlip
    params:
      p: 0.5
  - name: RandomVerticalFlip
    params:
      p: 0.5
  # - name: RandomColorJitter
  #   params:
  #     p: 0.5
  #     brightness: 0.2
  #     contrast: 0.2
  # - name: RandomGamma
  #   params:
  #     p: 0.5
  #     gamma_range: [0.8, 1.2]
  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

valid_list: [ 'Magrabia' ]
valid_transform:
  - name: ToTensor
  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
