# Simple MaskFormer 测试配置文件
# 支持强制匹配和匈牙利匹配两种模式

# 基础设置
seed: 42
epochs: 2  # 测试用小epoch数
batch_size: 2
use_amp: true
max_checkpoints: 2
dataset_type: 'RIGA'
save_dir: './exp_simple_maskformer_test'

# 模型配置
model:
  # SimpleMaskFormer 基础参数
  in_channels: 3
  num_classes: 3  # bg, ring, cup
  num_experts: 6
  num_extra_queries: 0
  
  # 强制匹配模式配置 (设为true启用强制匹配，false使用匈牙利匹配)
  force_matching: false  # 测试匈牙利匹配模式
  
  # Encoder配置
  backbone_encoder_name: "resnet34"
  backbone_encoder_weights: "imagenet"
  
  # Decoder配置
  backbone_decoder_channels: [256, 128, 64, 32, 16]
  backbone_use_batchnorm: true
  backbone_upsample_mode: 'interp'
  
  # Mask features配置
  mask_dim: 64
  mask_pixel_idxs: [-4, -3, -2]
  
  # Predictor配置
  decoder_nheads: 8
  decoder_dim_feedforward: 384
  decoder_dec_layers: 3
  decoder_pre_norm: false
  decoder_num_feature_levels: 3
  decoder_use_pos_emb: false
  decoder_non_object: true  # 匈牙利匹配模式下可以为true
  decoder_mask_threshold: 0.5
  decoder_mask_embed_type: 'sum_mask'
  decoder_cls_target_type: 'single'

# 损失函数配置
loss:
  num_classes: 3
  force_matching: false  # 与model.force_matching保持一致
  
  # 匈牙利匹配器配置
  matcher_cost_class: 1
  matcher_cost_mask: 1
  matcher_cost_dice: 1
  
  # 损失权重
  eos_coef: 1
  cost_weight: [2.0, 5.0, 5.0]
  non_object: true
  no_object_weight: null
  
  # 深监督配置
  ds_loss_weights: [1.0, 0.8, 0.6, 0.4]
  disable_ds: false
  ds_avg_type: 'v0'
  cls_type: null  # null为默认交叉熵，可选'focal'

# 优化器配置
optimizer:
  type: 'AdamW'
  weight_decay: 1e-4
  eps: 1e-8
  betas: [0.9, 0.999]
  amsgrad: false

# 学习率调度器配置
schelduler:
  use_cosine_scheduler: true
  base_lr: 1e-4  # 测试用较小学习率
  min_lr: 1e-6
  warmup: 1