# MaskFormer: CE分类 + Beta分割 + 直接匹配
# 特点: Cross-Entropy分类损失 + Beta分布分割损失 + Direct匹配算法
# 简化版本，使用传统CE分类和直接匹配，适合快速训练和调试

# 数据集配置
dataset:
  type: 'RIGA'
  config_path: './codes/configs/RIGA.yaml'

# 实验输出配置
experiment:
  save_dir: './exp/v3_ce_beta_direct'
  max_checkpoints: 3
  
# 训练配置
training:
  seed: 42
  epochs: 80  # 直接匹配收敛更快
  batch_size: 10  # 可以用更大的batch size
  use_amp: true
  num_workers: 4
  
  # 学习率配置 - CE模式可以用更高学习率
  learning_rate: 2e-3
  min_learning_rate: 1e-5
  
  # 优化器配置
  optimizer_type: 'AdamW'
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8
  
  # 调度器配置
  use_cosine_scheduler: true
  warmup_epochs: 5

# 模型配置
model:
  in_channels: 3
  num_cls_classes: 12
  num_queries: 12
  
  # Backbone配置
  backbone_encoder_name: "resnet34"
  backbone_encoder_weights: "imagenet"
  backbone_decoder_channels: [256, 128, 64, 32, 16]
  backbone_use_batchnorm: true
  
  # 掩码特征配置
  mask_dim: 64
  mask_pixel_idxs: [-4, -3, -2]
  
  # Predictor配置
  predictor_nheads: 8
  predictor_dim_feedforward: 384
  predictor_dec_layers: 3
  predictor_non_object: false  # 直接匹配不需要背景类
  
  # EDL配置
  predictor_cls_type: 'single'
  predictor_attn_mask_type: 'mask'
  predictor_mask_threshold: 0.5

# 损失函数配置 - CE分类 + Beta分割 + 直接匹配
loss:
  num_cls_classes: 12
  
  # 直接匹配 - 跳过匈牙利算法
  use_direct_matching: true
  
  # 损失类型 - 核心配置
  cls_loss_type: 'ce'          # CE分类损失
  seg_edl_as_dirichlet: false  # Beta分割损失
  dice_on_logits: false
  
  # 权重配置 - CE模式权重
  branch_weight_cls: 1.0
  branch_weight_seg: 1.0
  loss_weight_cls: 2.0   # CE分类权重
  loss_weight_kl: 0.0    # CE模式无KL损失
  loss_weight_dice: 1.0
  loss_weight_edl_mask: 1.0
  
  # 其他配置
  eos_coef: 0.1
  non_object: false  # 直接匹配不使用背景类
  annealing_steps: 5000
  
  # 深监督
  use_deep_supervision: true
  ds_loss_weights: [1.0, 0.8, 0.6, 0.4]
  ds_avg_type: 'sum'