# EDL MaskFormer 配置版本2: EDL分类 + Dirichlet分割 + 匈牙利匹配
# 完整EDL训练配置，分类和分割都使用证据学习

# 数据集配置
dataset:
  type: 'RIGA'
  config_path: './codes/configs/RIGA.yaml'

# 实验输出配置
experiment:
  save_dir: './exp/v2_edl_dirichlet_hungarian'
  max_checkpoints: 3
  
# 训练配置
training:
  seed: 42
  epochs: 120
  batch_size: 6  # Dirichlet模式内存消耗更大
  use_amp: true
  num_workers: 4
  
  # 学习率配置 - 稍微降低学习率
  learning_rate: 8e-4
  min_learning_rate: 1e-5
  
  # 优化器配置
  optimizer_type: 'AdamW'
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8
  
  # 调度器配置
  use_cosine_scheduler: true
  warmup_epochs: 15

# 模型配置
model:
  in_channels: 3
  num_cls_classes: 12
  num_queries: 12
  
  # Backbone配置
  backbone_encoder_name: "resnet34"
  backbone_encoder_weights: "imagenet"
  backbone_decoder_channels: [256, 128, 64, 32, 16]
  backbone_use_batchnorm: true
  
  # 掩码特征配置
  mask_dim: 64
  mask_pixel_idxs: [-4, -3, -2]
  
  # Predictor配置
  predictor_nheads: 8
  predictor_dim_feedforward: 384
  predictor_dec_layers: 3
  predictor_non_object: true
  
  # EDL配置
  predictor_cls_type: 'single'
  predictor_attn_mask_type: 'uncertainty_threshold'
  predictor_uncertainty_threshold: 0.3

# 损失函数配置 - EDL分类 + Dirichlet分割  
loss:
  num_cls_classes: 12
  
  # 匹配器配置
  matcher_cost_class: 2.0
  matcher_cost_dice: 4.0  # 降低dice权重，因为Dirichlet更复杂
  matcher_cost_evidence: 1.5
  matcher_cost_class_type: 'evidence'
  
  # 损失类型 - 核心配置
  cls_loss_type: 'edl'        # EDL分类损失
  seg_edl_as_dirichlet: true  # Dirichlet分割损失
  dice_on_logits: false
  
  # 权重配置 - 调整Dirichlet模式权重
  branch_weight_cls: 1.0
  branch_weight_seg: 1.2  # 增加分割权重
  loss_weight_cls: 1.0
  loss_weight_kl: 0.15   # 增加KL权重
  loss_weight_dice: 0.8   # 降低DICE权重
  loss_weight_edl_mask: 1.2  # 增加EDL mask权重
  
  # 其他配置
  eos_coef: 0.1
  non_object: true
  annealing_steps: 15000  # 延长退火步数
  use_direct_matching: false
  
  # 深监督
  use_deep_supervision: true
  ds_loss_weights: [1.0, 0.8, 0.6, 0.4]
  ds_avg_type: 'sum'